if(NOT DEFINED ENGINE OR NOT DEFINED FIXTURE OR NOT DEFINED TEST_DIR)
    message(FATAL_ERROR "Missing metadata CLI test arguments")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")
file(SHA256 "${FIXTURE}" before)
execute_process(COMMAND "${ENGINE}" metadata canonical "${FIXTURE}"
    RESULT_VARIABLE status OUTPUT_VARIABLE canonical ERROR_VARIABLE error)
if(NOT status EQUAL 0 OR NOT error STREQUAL "")
    message(FATAL_ERROR "Canonical metadata command failed: ${status} ${error}")
endif()
file(WRITE "${TEST_DIR}/canonical.json" "${canonical}")
execute_process(COMMAND "${ENGINE}" metadata canonical "${TEST_DIR}/canonical.json"
    RESULT_VARIABLE status OUTPUT_VARIABLE repeated ERROR_VARIABLE error)
if(NOT status EQUAL 0 OR NOT repeated STREQUAL canonical)
    message(FATAL_ERROR "Canonical metadata did not round trip")
endif()
file(WRITE "${TEST_DIR}/invalid.json" "{\"schema_version\":1,\"schema_version\":2}")
execute_process(COMMAND "${ENGINE}" metadata canonical "${TEST_DIR}/invalid.json"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 1 OR NOT output STREQUAL "" OR NOT error MATCHES "duplicate_field")
    message(FATAL_ERROR "Invalid metadata must fail without publishing output")
endif()
string(REPEAT " " 4194305 oversized)
file(WRITE "${TEST_DIR}/oversized.json" "${oversized}")
execute_process(COMMAND "${ENGINE}" metadata verify "${TEST_DIR}/oversized.json"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 1 OR NOT output STREQUAL "" OR NOT error MATCHES "input_too_large")
    message(FATAL_ERROR "Oversized file must fail closed")
endif()
execute_process(COMMAND "${ENGINE}" metadata verify "${TEST_DIR}/missing/snapshot.json"
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT status EQUAL 1 OR NOT output STREQUAL "" OR NOT error MATCHES "read failed")
    message(FATAL_ERROR "Missing file must report a read error")
endif()
file(SHA256 "${FIXTURE}" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Inspection modified the source snapshot")
endif()
