file(REMOVE_RECURSE "${TEST_DIR}")
file(MAKE_DIRECTORY "${TEST_DIR}")
execute_process(COMMAND "${FIXTURE_WRITER}" --fixture "${TEST_DIR}/input"
    RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "session fixture failed")
endif()
foreach(name first second)
    execute_process(COMMAND "${ENGINE}" session pack
        "${TEST_DIR}/input/source.json" "${TEST_DIR}/input/source.journal" "${TEST_DIR}/${name}"
        RESULT_VARIABLE result OUTPUT_VARIABLE packed ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT packed MATCHES "SESSION         VERIFIED")
        message(FATAL_ERROR "session pack failed: ${error}")
    endif()
    execute_process(COMMAND "${ENGINE}" session verify "${TEST_DIR}/${name}"
        RESULT_VARIABLE result OUTPUT_VARIABLE verified ERROR_VARIABLE error)
    if(NOT result EQUAL 0 OR NOT verified STREQUAL packed)
        message(FATAL_ERROR "session verify disagrees with pack: ${error}")
    endif()
endforeach()
file(READ "${TEST_DIR}/first/manifest.json" first)
file(READ "${TEST_DIR}/second/manifest.json" second)
if(NOT first STREQUAL second)
    message(FATAL_ERROR "identical inputs must produce identical manifests")
endif()
file(SHA256 "${TEST_DIR}/first/metadata.json" metadata_hash)
file(SHA256 "${TEST_DIR}/first/market.journal" journal_hash)
string(JSON recorded_metadata GET "${first}" metadata sha256)
string(JSON recorded_journal GET "${first}" journal sha256)
if(NOT metadata_hash STREQUAL recorded_metadata OR NOT journal_hash STREQUAL recorded_journal)
    message(FATAL_ERROR "manifest fingerprints disagree with independent CMake SHA256")
endif()
file(SHA256 "${TEST_DIR}/input/source.journal" source_hash)
if(NOT source_hash STREQUAL journal_hash)
    message(FATAL_ERROR "packing changed original journal bytes")
endif()
execute_process(COMMAND "${ENGINE}" session pack
    "${TEST_DIR}/input/source.json" "${TEST_DIR}/input/source.journal" "${TEST_DIR}/first"
    RESULT_VARIABLE result ERROR_VARIABLE error OUTPUT_QUIET)
if(result EQUAL 0 OR NOT error MATCHES "directory_exists")
    message(FATAL_ERROR "existing session was not protected")
endif()
file(WRITE "${TEST_DIR}/second/metadata.json" "{}")
execute_process(COMMAND "${ENGINE}" session verify "${TEST_DIR}/second"
    RESULT_VARIABLE result ERROR_VARIABLE error OUTPUT_VARIABLE output)
if(result EQUAL 0 OR NOT error MATCHES "fingerprint_mismatch" OR output MATCHES "VERIFIED")
    message(FATAL_ERROR "corrupt session must fail without a success report")
endif()
file(REMOVE "${TEST_DIR}/first/manifest.json")
execute_process(COMMAND "${ENGINE}" session verify "${TEST_DIR}/first"
    RESULT_VARIABLE result ERROR_VARIABLE error OUTPUT_QUIET)
if(result EQUAL 0 OR NOT error MATCHES "incomplete_session")
    message(FATAL_ERROR "missing final manifest must fail closed")
endif()
